name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk+fx

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build and check with Gradle
        run: ./gradlew check --warning-mode all --info --stacktrace -PextraCompilerArgs="-Xlint:unchecked"

      - name: Install dos2unix (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install dos2unix

      - name: Install dos2unix (macOS)
        if: runner.os == 'macOS'
        run: brew install dos2unix

      - name: Perform IO redirection test (*NIX)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        working-directory: ${{ github.workspace }}/text-ui-test
        run: ./runtest.sh

      - name: Perform IO redirection test (Windows)
        if: runner.os == 'Windows'
        working-directory: ${{ github.workspace }}/text-ui-test
        shell: cmd
        run: runtest.bat
